---
title: "Dmaps Colombia"
author: "jpmarindiaz"
date: "2017-07-25"
output:
  html_document
---

```{r, include=FALSE, cache=FALSE}
library(dmaps)
```

# A bunch of examples for Colombia

## Number of schools per department

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data <- read.csv(system.file("data/co/ncolegios-departamento.csv",package="dmaps"))
dmaps(data, "col_departments", regionCols = "departamento", valueCol = "count")
```

```{r, echo=FALSE, warning=FALSE}

opts <- list(legend = list(choropleth = list(title = "legend Title")))
dmaps(data, "col_departments", regionCols = "departamento", valueCol = "count", opts = opts)
```

```{r, echo=FALSE, warning=FALSE}
d <- read_csv(system.file("data/co/co_municipalities-2-vars.csv", package = "dmaps"),
              col_types = cols(code = "c"))
mapName <- "col_municipalities"
names(d)
dmaps(d ,mapName,
      valueCol = "conf_uso_2",
      regionCols = c("municipio","departamento"),
      regions = "Altillanura",
      opts = opts
)
```

```{r}
d <- read_csv(system.file("data/co/co_municipalities-2-vars.csv", package = "dmaps"))
mapName <- "col_municipalities"
opts <- list(
  defaultFill = "#000000",
  borderColor = "#9FCC44",
  borderWidth = 0.1,
  highlightFillColor = "#99FFAA",
  highlightBorderWidth = 0,
  palette = "viridis",
  nLevels = 5
  #projectionOpts = list(scale = 20)
)

dmaps(mapName, data = d,
      valueCol = "conf_uso_2",
      codeCol = "code",
      regions = "Cesar",
      opts = opts
)

```



```{r}
casosgeo <- read_csv(system.file("data/co/casosgeo.csv", package = "dmaps"))
opts <- list(
  tooltip = list(choropleth = list(template = "DEPTO: {departamento}<br> <strong>TOTAL</strong>: {Total}")),
  legend =  list(choropleth = list(title = "TItle"))
)
viz <- dmaps(data = casosgeo, "col_departments",
              valueCol = "Total",
              regionCols = c("departamento"),
             opts = opts)

viz
```


